### ISSUE TITLE
RenderTransformOrigin?

### ISSUE THREAD

**Issue by suchja** [MK-NEUKO/BallSpiel#1]
@MK-NEUKO Super, dass du auch an dieser Übung teilnimmst!!!

Wofür verwendest du an [dieser](https://github.com/MK-NEUKO/BallSpiel/blob/c64f5282367bf435e003a760a9ce52b60d0cc4f7/BallSpiel/MainWindow.xaml#L9) Stelle das `RenderTransformOrigin`?

**Comment by MK-NEUKO** [comment]
Ehrlichgesagt weiß ich nicht, was das bedeuten. Ich werde es mir zur Aufgabe machen das herauszufinden. Ich vermute, das das bei der Projekterzeugung entstanden ist, ich habe das nicht explizit eingeben.

**Comment by suchja** [comment]
Es könnte sein, dass du versucht hast im Designer das `Grid` mit der Maus zu verschieben oder irgendwie so. Vielleicht ist es auch ein Fehler im Designer.

Das `RenderTransformOrigin` kannte ich bisher auch noch nicht. Es wird scheinbar im Bereich Animation eingesetzt.

**Comment by MK-NEUKO** [comment]
Soweit ich das verstehe, ist RenderTransformOrigin ein point-Objekt eines Elements, von dem aus das Element gedreht, etc. werden kann. Es erwartet relative x, y-werte, (0, 0 währe die linke obere Ecke, 0.5, 0.5 die Mitte und 1, 1 ist rechts unten).
Ich hab ein Dickes Buch zur WPF, dort habe ich es nachgeschlagen.

**Comment by MK-NEUKO** [comment]
Vermutlich habe ich es versehentlich, wie schon gesagt, durch ein verschieben des Grid hervorgerufen.

**Comment by suchja** [comment]
Cool, welches Buch hast du und bist du zufrieden damit?

**Comment by MK-NEUKO** [comment]
https://www.rheinwerk-verlag.de/windows-presentation-foundation_4949/
Wie ich es finde? Für das erste mal hat es gut funktioniert. Ich hab das Buch erst seit gestern.
Ich werde in den nächsten Tagen schildern warum und mit welchen Zielen ich das Ganze mache. Dann aber im Kurs selbst.
