### ISSUE TITLE
Änderungen in MainWindow.xaml 

### ISSUE THREAD

**Issue by MK-NEUKO** [MK-NEUKO/BallSpiel#2]
Ich verstehe nicht so richtg, warum so viele Änderung in der MainWindow.xaml automatische gemacht wurden?
Es gibt also noch viel zu lernen.

**Comment by MK-NEUKO** [comment]
@suchja
Ich habe die Methode zum Bewegen des Balls per Pfeiltasten hinzugefügt.

**Comment by suchja** [comment]
Das sieht doch alles schon mal ganz gut aus! Welche automatischen Änderungen am `MainWindow` meinst du denn?

**Comment by MK-NEUKO** [comment]
Ok, ich hab soweit alles verstanden. Quellcodänderungen wirken eben dynamisch auf die xaml und umgekehrt.

**Comment by suchja** [comment]
Also Quellcodeänderungen (im `MainWindow.xaml.cs`) sollten sich nicht auf die `MainWindow.xaml` auswirken. Wenn du im Designer neue Elemente aus der Toolbox auf die Oberfläche ziehst, dann wird das entsprechend in der `MainWindow.xaml` angepasst. Das gleiche gilt für Änderungen im Bereich Eigenschaften.

**Comment by MK-NEUKO** [comment]
Dann kann ich nicht richtig nachvollziehen, wie die Änderungen entstanden sind. Ich werde beim nächsten WPF Projekt verstärkt drauf achten.

**Comment by suchja** [comment]
Das ist eine gute Idee. Am besten du schickst dann einfach mal ein Beispiel. Dann kommen wir bestimmt gemeinsam auf eine Antwort.
